name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Cập nhật tên nhánh tùy theo tên nhánh chính của bạn

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .  # Thay đổi tên thư mục nếu file .ps1 không ở trong thư mục gốc của repository
